import type { DraftPlayer } from './types'

export const draftPlayers: DraftPlayer[] = [
  { id: 'bijan-robinson', name: 'Bijan Robinson', position: 'RB', nflTeam: 'ATL', bye: 12, projectedPoints: 285.4, adp: 1.4, tier: 1, notes: 'Elite three-down usage and receiving ceiling.' },
  { id: 'jahmyr-gibbs', name: 'Jahmyr Gibbs', position: 'RB', nflTeam: 'DET', bye: 8, projectedPoints: 278.9, adp: 2.1, tier: 1, notes: 'Explosive runner with premium PPR value.' },
  { id: 'jamarr-chase', name: "Ja'Marr Chase", position: 'WR', nflTeam: 'CIN', bye: 10, projectedPoints: 312.6, adp: 2.8, tier: 1, notes: 'Difference-making target share and weekly ceiling.' },
  { id: 'justin-jefferson', name: 'Justin Jefferson', position: 'WR', nflTeam: 'MIN', bye: 6, projectedPoints: 304.2, adp: 3.5, tier: 1, notes: 'Elite volume with league-winning upside.' },
  { id: 'ceedee-lamb', name: 'CeeDee Lamb', position: 'WR', nflTeam: 'DAL', bye: 7, projectedPoints: 296.8, adp: 4.6, tier: 1, notes: 'High-volume WR1 with a safe weekly floor.' },
  { id: 'saquon-barkley', name: 'Saquon Barkley', position: 'RB', nflTeam: 'PHI', bye: 9, projectedPoints: 262.7, adp: 6.2, tier: 1, notes: 'Touchdown ceiling in an elite rushing offense.' },
  { id: 'amonra-st-brown', name: 'Amon-Ra St. Brown', position: 'WR', nflTeam: 'DET', bye: 8, projectedPoints: 286.4, adp: 7.1, tier: 1, notes: 'Reliable targets and strong red-zone role.' },
  { id: 'puka-nacua', name: 'Puka Nacua', position: 'WR', nflTeam: 'LAR', bye: 8, projectedPoints: 279.5, adp: 8.3, tier: 2, notes: 'Alpha usage with yards-after-catch upside.' },
  { id: 'malik-nabers', name: 'Malik Nabers', position: 'WR', nflTeam: 'NYG', bye: 14, projectedPoints: 272.8, adp: 9.4, tier: 2, notes: 'Massive target share creates a strong floor.' },
  { id: 'nico-collins', name: 'Nico Collins', position: 'WR', nflTeam: 'HOU', bye: 6, projectedPoints: 265.1, adp: 10.8, tier: 2, notes: 'Efficient downfield role in a productive attack.' },
  { id: 'breece-hall', name: 'Breece Hall', position: 'RB', nflTeam: 'NYJ', bye: 9, projectedPoints: 249.3, adp: 12.1, tier: 2, notes: 'Dual-threat back with breakaway ability.' },
  { id: 'derrick-henry', name: 'Derrick Henry', position: 'RB', nflTeam: 'BAL', bye: 7, projectedPoints: 242.8, adp: 13.5, tier: 2, notes: 'Touchdown-driven RB1 with heavy volume.' },
  { id: 'aj-brown', name: 'A.J. Brown', position: 'WR', nflTeam: 'PHI', bye: 9, projectedPoints: 253.7, adp: 14.2, tier: 2, notes: 'Dominant route winner with spike-week potential.' },
  { id: 'brian-thomas', name: 'Brian Thomas Jr.', position: 'WR', nflTeam: 'JAX', bye: 8, projectedPoints: 248.5, adp: 15.9, tier: 2, notes: 'Ascending vertical threat with WR1 upside.' },
  { id: 'devon-achane', name: "De'Von Achane", position: 'RB', nflTeam: 'MIA', bye: 12, projectedPoints: 231.4, adp: 17.2, tier: 2, notes: 'Game-breaking efficiency and receiving value.' },
  { id: 'josh-jacobs', name: 'Josh Jacobs', position: 'RB', nflTeam: 'GB', bye: 5, projectedPoints: 226.9, adp: 18.4, tier: 2, notes: 'Stable workload in a balanced offense.' },
  { id: 'brock-bowers', name: 'Brock Bowers', position: 'TE', nflTeam: 'LV', bye: 8, projectedPoints: 238.6, adp: 19.1, tier: 1, notes: 'Rare target volume creates a positional edge.' },
  { id: 'ladd-mcconkey', name: 'Ladd McConkey', position: 'WR', nflTeam: 'LAC', bye: 12, projectedPoints: 239.7, adp: 20.6, tier: 3, notes: 'High-percentage targets support a PPR breakout.' },
  { id: 'lamar-jackson', name: 'Lamar Jackson', position: 'QB', nflTeam: 'BAL', bye: 7, projectedPoints: 372.8, adp: 21.8, tier: 1, notes: 'Elite rushing floor plus week-winning ceiling.' },
  { id: 'josh-allen', name: 'Josh Allen', position: 'QB', nflTeam: 'BUF', bye: 7, projectedPoints: 368.9, adp: 23.0, tier: 1, notes: 'Premium rushing touchdowns and passing volume.' },
  { id: 'drake-london', name: 'Drake London', position: 'WR', nflTeam: 'ATL', bye: 12, projectedPoints: 232.3, adp: 24.4, tier: 3, notes: 'Strong target profile with touchdown upside.' },
  { id: 'jonathan-taylor', name: 'Jonathan Taylor', position: 'RB', nflTeam: 'IND', bye: 11, projectedPoints: 218.6, adp: 25.2, tier: 3, notes: 'Proven runner with goal-line control.' },
  { id: 'trey-mcbride', name: 'Trey McBride', position: 'TE', nflTeam: 'ARI', bye: 8, projectedPoints: 217.4, adp: 26.7, tier: 1, notes: 'High route participation and target volume.' },
  { id: 'garrett-wilson', name: 'Garrett Wilson', position: 'WR', nflTeam: 'NYJ', bye: 9, projectedPoints: 226.2, adp: 27.9, tier: 3, notes: 'Target-earning profile with rebound potential.' },
  { id: 'jalen-hurts', name: 'Jalen Hurts', position: 'QB', nflTeam: 'PHI', bye: 9, projectedPoints: 351.6, adp: 29.3, tier: 1, notes: 'Rushing scores preserve an elite fantasy floor.' },
  { id: 'chase-brown', name: 'Chase Brown', position: 'RB', nflTeam: 'CIN', bye: 10, projectedPoints: 207.8, adp: 30.8, tier: 3, notes: 'Three-down opportunity with receiving growth.' },
  { id: 'tee-higgins', name: 'Tee Higgins', position: 'WR', nflTeam: 'CIN', bye: 10, projectedPoints: 214.7, adp: 32.2, tier: 3, notes: 'Efficient scoring role with weekly WR1 upside.' },
  { id: 'george-kittle', name: 'George Kittle', position: 'TE', nflTeam: 'SF', bye: 14, projectedPoints: 198.5, adp: 34.1, tier: 2, notes: 'Efficient difference-maker at a scarce position.' },
  { id: 'james-cook', name: 'James Cook', position: 'RB', nflTeam: 'BUF', bye: 7, projectedPoints: 199.2, adp: 35.6, tier: 3, notes: 'Efficient lead back in a high-scoring offense.' },
  { id: 'terry-mclaurin', name: 'Terry McLaurin', position: 'WR', nflTeam: 'WAS', bye: 12, projectedPoints: 207.6, adp: 37.1, tier: 4, notes: 'Veteran route winner with strong scoring equity.' },
  { id: 'kyren-williams', name: 'Kyren Williams', position: 'RB', nflTeam: 'LAR', bye: 8, projectedPoints: 194.8, adp: 38.5, tier: 3, notes: 'Goal-line usage supports a strong touchdown floor.' },
  { id: 'jayden-daniels', name: 'Jayden Daniels', position: 'QB', nflTeam: 'WAS', bye: 12, projectedPoints: 338.4, adp: 40.2, tier: 2, notes: 'Rushing production drives elite weekly upside.' },
  { id: 'dj-moore', name: 'DJ Moore', position: 'WR', nflTeam: 'CHI', bye: 5, projectedPoints: 201.9, adp: 42.0, tier: 4, notes: 'Versatile playmaker with proven target earning.' },
  { id: 'davante-adams', name: 'Davante Adams', position: 'WR', nflTeam: 'LAR', bye: 8, projectedPoints: 198.7, adp: 43.6, tier: 4, notes: 'Red-zone craft keeps his ceiling intact.' },
  { id: 'sam-laporta', name: 'Sam LaPorta', position: 'TE', nflTeam: 'DET', bye: 8, projectedPoints: 184.3, adp: 45.1, tier: 2, notes: 'Strong scoring environment and route participation.' },
  { id: 'david-montgomery', name: 'David Montgomery', position: 'RB', nflTeam: 'DET', bye: 8, projectedPoints: 181.6, adp: 47.5, tier: 4, notes: 'Reliable goal-line role with usable weekly floor.' },
  { id: 'patrick-mahomes', name: 'Patrick Mahomes', position: 'QB', nflTeam: 'KC', bye: 10, projectedPoints: 326.5, adp: 49.2, tier: 2, notes: 'Elite passer with stable high-end production.' },
  { id: 'buffalo-dst', name: 'Buffalo Bills', position: 'D/ST', nflTeam: 'BUF', bye: 7, projectedPoints: 132.4, adp: 128.0, tier: 1, notes: 'Strong pressure rate and turnover potential.' },
  { id: 'pittsburgh-dst', name: 'Pittsburgh Steelers', position: 'D/ST', nflTeam: 'PIT', bye: 5, projectedPoints: 128.1, adp: 134.0, tier: 1, notes: 'High-impact pass rush creates weekly upside.' },
  { id: 'brandon-aubrey', name: 'Brandon Aubrey', position: 'K', nflTeam: 'DAL', bye: 7, projectedPoints: 151.2, adp: 139.0, tier: 1, notes: 'Range and team scoring chances create an edge.' },
  { id: 'cameron-dicker', name: 'Cameron Dicker', position: 'K', nflTeam: 'LAC', bye: 12, projectedPoints: 144.7, adp: 145.0, tier: 1, notes: 'Accurate option attached to a capable offense.' },
]
